config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home' #needs action not url thats why home_path doesnt work
  get '/help', to: 'static_pages#help', as: 'help'
  #as: changes name of path/url i.e help_path or help_url
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #patch "/users/:id/edit", to: "users#update" as 'update'   GAH! FUCK! whatever its not a huge deal.
  #how to make sow /edit doesnt dissapear after failed patch/put
  #can copy and paste urls able to edit other users
  resources :users do#, :except => :update
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :create, :new, :update]
  #add update?
  resources :microposts, only: [ :destroy]
  post '/', to: 'microposts#create', as: 'microposts'
  #GONNA LEARN HOW TO MODIFY URL!!!
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id",
                                  dependent: :destroy
    has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id",
                                  dependent: :destroy
                                  
    #used followed_id as foreign key, automatically dependent since through?
    #not in database so dependent is not required
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships #, source: :follower optional
    
    #implentating shares
    has_many :shares, foreign_key: "shared_id", dependent: :destroy
    has_many :sharedposts, through: :shares
    
    #order
    scope :activated, -> { where(activated: true) }
    default_scope -> { order(name: :asc) }
    
    #assigning attributes not in the database
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email # self keyword is optional on right hand side
    before_create :create_activation_digest
    
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, 
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false }
    validates :password, length: {minimum: 6}, presence: true, allow_nil: true
    has_secure_password #only for sign up?               #excuse me??
    
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    #returns a random token.
    def User.new_token
      SecureRandom.urlsafe_base64
    end
    
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest("#{remember_token}")) #unecessary can just put remember_token
    end
    
    # returns true if the given token matches the digest
    def authenticated?(att, token)
      #removing repetitive _digest
      digest = send("#{att}_digest") #send automatically puts self. in model
      if digest.nil?
        return false
      end
      BCrypt::Password.new(digest).is_password?(token)
    end
    
    # Forgets a user
    def forget
      update_attribute(:remember_digest, nil)
    end
    
    def activate
      #self. is automatic with update
      #diff between update_columns and update_attributes? both work
      update_columns(activated: true, activated_at: Time.zone.now)
    end
    
    def send_activation_email
      UserMailer.account_activation(self).deliver_now
    end
    
    # sets the passwrod reset attr
    def reset
        self.reset_token = User.new_token
        self.update_attributes(reset_digest: User.digest(reset_token),
                              reset_sent_at: Time.zone.now)
    end
    
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end
    
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end
    
    #tutorial feed, grabs from database, organizes all of them
    #returns active record
  def feed
      #(following_ids = following.map(&:id)) == following_ids ;cause of active record
      #? does interpolation so you dont need to join array of ids into a string
   #more efficient cause doesnt have to pull everything into an array
    following_ids = "SELECT followed_id FROM relationships
                    WHERE follower_id = :user_id"
    shared_micropost_ids = "SELECT sharedpost_id FROM shares
                            WHERE shared_id IN (#{following_ids})" 
   Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id 
                    OR id IN (#{shared_micropost_ids})", 
                      user_id: id)
  end
    
#    my feed, organizes them by time in packs, bad
#    def feed
#      feed = Micropost.where("user_id = ?", id)
      #changes activerecord to an array, how to make it remain active record
#      self.following.each do |f|
#       f_posts = Micropost.where("user_id = ?", f.id)
#        feed += f_posts
#      end
#      feed
#     end returns array

    #remember about self
    #follows a user.
    #i guess << also saves
    def follow(other_user)
      following << other_user
    end
    
    #Unfollow a user
    def unfollow(other_user)
      following.delete(other_user)
    end
    
    def following?(other_user)
      following.include?(other_user)
    end
    
    def followed_by?(other_user)
      followers.include?(other_user)
    end
    
    def share(micropost)
      sharedposts << micropost
    end
    
    def shared?(micropost)
      sharedposts.include?(micropost)
    end
    
    def unshare(micropost)
      sharedposts.delete(micropost)
    end
    
  def User.followjosh()
    a = User.find_by(email: "joshuaolivares@utexas.edu")
    User.all.each do |u|
      unless (u == a) || (u.following?(a))
        u.follow(User.find_by(email: "joshuaolivares@utexas.edu"))
      end
    end
  end
    
    private
      def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
      end
      
      def downcase_email
        email.downcase!
      end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :index, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  
  def new
    @user = User.new #why do i need this
  end
  def show
    @user = User.find(params[:id]) # id is what is after users/
    #return makes sure it doesnt go to view
    # will only show activated users
    #can make it so only activated users can look at others if 
    #i want by current_user.activated?
    
    #NOTE THE AND HERE
    redirect_to root_path and return unless @user.activated?
    #debugger                     #how can we make users non numbers.
                                   #in routes.RB probably
    @microposts = @user.microposts.paginate(page: params[:page])
  end                            
  
  def create
    @user = User.new(user_params) #what?
    if @user.save
      #log_in @user
      #flash[:success] = "Welcome :P"
      @user.send_activation_email
      flash[:info] = "please check your email to activate your account"
      redirect_to root_url #shorthand for user_url(@user) diff between url and path??
     else
      render 'new'
    end
  end
  
  def edit
    #failed edit does change url but :id is still there in url
  end

#updates password too prob want to make it so need previous password
  def update
    #why is @user not defined
    if @user.update_attributes(user_params)#not given!!!
      flash[:success] = "Changes saved"
      redirect_to @user
    else
      render 'edit'
      #diff between render and redirect? 
      #doesnt give errors cause treating error as .now
    end
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers 
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def correct_user
    @user = User.find params[:id] #follows id of user, params[:user][:id]
    unless current_user?(@user) 
      flash[:warning] = "No,no,no ;)"
      redirect_to root_path 
    end
  end
  #should i change it to @user???cause if entering restricted edit 
  #then logging into not that id for the restricted edit
  #that leads you to the home page not the profile nor edit page
  def index
    @users = User.where(activated: true).paginate(page: params[:page], per_page: 15)
  end
  
  def destroy
      name = User.find(params[:id]).name
      User.find(params[:id]).delete
      flash[:success] = "#{name} deleted"
      redirect_to users_path #render wont change url. no action
      name = nil
  end
  
  def admin_user
    unless current_user.admin?
      flash[:error] = "YOU CHEECKY BASTARD"
      redirect_to users_path
    end
  end
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation) #review this
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
  #returns Gravatar for given user
  def gravatar_for(user, options = {size: 80}) # or can just use argument keyword down below without options
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build,
                remote: true) do |f| %>
    <div> <%= hidden_field_tag :followed_id, @user.id %> </div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<%end%>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form" >
    <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
    <% else %>
        <%= render 'follow' %>
    <%end%>
</div>
<%end%>

app/views/users/_forms.html.erb
<!-- when doing a partial variables arent transferable -->
<!-- either all variable use is in partial or view -->

<%= form_for(@user, url: yield(:path)) do |f| %> <!-- why do i need the url here for it to work?-->
<%= render 'shared/error_messages', object: f.object %>
            
<%= f.label :name %> <!--whats the point fo the symbols for the labels?-->
<%= f.text_field :name, class: 'form-control' %>
            
    <%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
            
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
            
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit yield(:button_text) , class: "btn btn-primary" %>
        <% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
        html: {method: :delete },
        remote: true) do |f| %>
<%= f.submit "Unfollow", class: "btn" %>
<%end%>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: "50x50" %> 
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
            data: { confirm: "Are you sure you want to delete #{user.name}?"} %>
    <%end%>
</li>

app/views/users/edit.html.erb
<% provide(:button_text, 'Save changes') %>
<% provide(:title, "edit user") %>
<% provide(:path, user_path(@user)) %>
<h1>Update your profile</h1> <!-- does h1 automatically center?-->

<div class = "row">
    <div class ="col-md-6 col-md-offset-3">

            <%= render 'users/forms' %>
        
        <div class="gravatar_edit">
            <%= gravatar_for @user %> <!-- calling the gravatar_for method that i wrote -->
            <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change profile pic</a>
        </div> <!-- rel='noopener makes it secure, no pop ups?? -->
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<div> <!-- having div tag here makes no difference -->
    <ul class="users">
        <%= render @users %> <!-- Prettty cool, sec 10.3.5!! 
                                and works with scopes!-->
    </ul>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:button_text, 'Create my account') %>
<% provide(:legal, 'true') %>
<% provide(:title, 'Sign up') %>
<% provide(:path, signup_path) %>
<h1 class = "center">SIGN UP!</h1> <!-- jumbo class? -->
<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= render 'users/forms' %>
        <p>
        Already have an account?<%= link_to "Log in!", login_path %> 
        </p>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <!-- aside tag? -->
  <aside class= "user_info">
    <section class= "user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class = "col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <ol class ="microposts">
      <%= render @microposts %>
    </ol>
    <!-- need to specify @microposts for paginate cause doing it in user view -->
    <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <%= gravatar_for @user %>
            <h1><%= @user.name %> </h1>
            <span><%= link_to "View profile", @user %></span>
            <span><b>Microposts:</b> <%= @user.microposts.count %> </span>
        </section>
        <section class="stats">
            <%= render 'shared/stats' %>
            <% if @users.any? %>
            <div class = "user_avatars">
                <% @users.each do |u| %>
                    <%= link_to gravatar_for(u, size: 30), u %>
                <%end%>
            </div>
            <%end%>
        </section>
    </aside>
    <div class="col-md-8">
        <h3><%= @title %></h3>
        <% if @users.any? %>
        <ul class="users follow">
            <%= render @users %>
        </ul>
        <%= will_paginate %>
        <%end%>
    </div>
</div>