config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home' #needs action not url thats why home_path doesnt work
  get '/help', to: 'static_pages#help', as: 'help'
  #as: changes name of path/url i.e help_path or help_url
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #patch "/users/:id/edit", to: "users#update" as 'update'   GAH! FUCK! whatever its not a huge deal.
  #how to make sow /edit doesnt dissapear after failed patch/put
  #can copy and paste urls able to edit other users
  resources :users do#, :except => :update
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:edit, :create, :new, :update]
  #add update?
  resources :microposts, only: [ :destroy]
  post '/', to: 'microposts#create', as: 'microposts'
  #GONNA LEARN HOW TO MODIFY URL!!!
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Joshua Olivares</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <% if yield(:legal)=='true' %>
      <li><%= link_to "legal", root_path %></li>
      <%end%>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample_app", root_path, id:"logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class ="dropdown">
              <a href='#' class= "dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_default.erb
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %> <!-- partial for older browsers -->
  </head>
  
  <body>
    <%= render 'layouts/header' %> <!-- partial for header -->
    <div class="container">
      <% flash.each do |mess_type, mess| %>
        <%= content_tag(:div, mess, class: "alert alert-#{mess_type}")%>
      <% end %>
      <%= yield %> <!--- the real shit it will render -->
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>